[package]
name = "minesweeper_x"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
ipml = { git = "https://github.com/impodog/ipml.git", version = "0.4.0" }
rand = "0.8.5"
